### ISSUE TITLE
Cannot import OpenEXR after installing it

### ISSUE THREAD

**Issue by monajalal** [sanguinariojoe/pip-openexr#34]
Can you please suggest a solution?

```
(pvrendering) (base) mona@mona-ThinkStation-P7:~/pvnet-rendering$ sudo pip install openexr
Collecting openexr
  Using cached OpenEXR-1.3.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
Installing collected packages: openexr
Successfully installed openexr-1.3.9
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
(pvrendering) (base) mona@mona-ThinkStation-P7:~/pvnet-rendering$ python run.py --type rendering
Traceback (most recent call last):
  File "run.py", line 24, in <module>
    globals()['run_' + args.type]()
  File "run.py", line 11, in run_rendering
    from blender.render_utils import Renderer, YCBRenderer
  File "/home/mona/pvnet-rendering/blender/render_utils.py", line 9, in <module>
    import OpenEXR
ImportError: No module named 'OpenEXR'
(pvrendering) (base) mona@mona-ThinkStation-P7:~/pvnet-rendering$ python
Python 3.5.3 (default, May 18 2017, 14:40:48) 
[GCC 5.4.1 20161019] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import OpenEXR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'OpenEXR'
>>> import openexr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'openexr'
>>> quit()

```

This is really weird because after installation, the package doesn't show in pip show result:
```
(pvrendering) (base) mona@mona-ThinkStation-P7:~/pvnet-rendering$ pip show openexr
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
WARNING: Package(s) not found: openexr
(pvrendering) (base) mona@mona-ThinkStation-P7:~/pvnet-rendering$ pip show OpenEXR
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
WARNING: Package(s) not found: OpenEXR
(pvrendering) (base) mona@mona-ThinkStation-P7:~/pvnet-rendering$ which -a python
/home/mona/pvnet-rendering/pvrendering/bin/python
/home/mona/anaconda3/bin/python
(pvrendering) (base) mona@mona-ThinkStation-P7:~/pvnet-rendering$ which python
/home/mona/pvnet-rendering/pvrendering/bin/python
(pvrendering) (base) mona@mona-ThinkStation-P7:~/pvnet-rendering$ which pip
/home/mona/pvnet-rendering/pvrendering/bin/pip

```

```
(base) mona@mona-ThinkStation-P7:~/pvnet-rendering$ echo $PATH
/usr/local/cuda-11.8/bin:/home/mona/pvnet-rendering/pvrendering/bin:/usr/local/cuda-11.8/bin:/home/mona/anaconda3/bin:/home/mona/anaconda3/condabin:/home/mona/.nvm/versions/node/v18.18.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/mona/Downloads/blender-2.79a-linux-glibc219-x86_64/2.79/python/bin
(base) mona@mona-ThinkStation-P7:~/pvnet-rendering$ echo $LD_LIBRARY_PATH
/usr/local/cuda-11.8/lib64:/usr/local/cuda-11.8/lib64::/home/mona/Downloads/blender-2.79a-linux-glibc219-x86_64/2.79/python/lib

```

**Comment by sanguinariojoe** [comment]
Hey Mona!

This repo is about to get closed because the python wrapper is getting
integrated onto the openexr library.

I suppose these bugs will not be there anymore

**Comment by monajalal** [comment]
@sanguinariojoe thanks a lot for your response. Any chance you may know how I can stay in the know when the new change will be effective? Is there a release date?

**Comment by sanguinariojoe** [comment]
You can follow the process here:

https://github.com/AcademySoftwareFoundation/openexr/pull/1581#issuecomment-1764588483

You can even give thumbs up or left comments to try to push them a bit to
merge it fast
